version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: portfolio_projects_db
      POSTGRES_USER: portfolio_projects_user
      POSTGRES_PASSWORD: portfolio_projects_password
    ports:
      - 5432:5432
    volumes:
      - db-portfolio-data:/var/lib/postgresql/data

volumes:
  db-portfolio-data: